### ISSUE TITLE
Add Linter to CI

### ISSUE THREAD

**Issue by rjsheperd** [sig-gis/triangulum#23]
Using [CLJ Kondo](https://github.com/clj-kondo/clj-kondo) 

- [x] Add [Clojure Lint Action](https://github.com/DeLaGuardo/clojure-lint-action)
```
- uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --lint src test
        github_token: ${{ secrets.GITHUB_TOKEN }}
```
- [x] Add Github Secret Token
